# Configurações básicas do site
title: Meu Site
description: Bem-vindo ao meu site pessoal!
url: "https://rodrigo-libc.github.io"
baseurl: ""

# Tema escuro remoto
remote_theme: sharadcodes/jekyll-theme-dark-reader
plugins:
  - jekyll-remote-theme
  - jekyll-paginate

# Configurações de blog
paginate: 5
show_posts: true

# Markdown
markdown: kramdown
kramdown:
  input: GFM


