title: Meu Site
description: Bem-vindo ao meu site pessoal!
url: "https://rodrigo-libc.github.io"
baseurl: ""

theme: jekyll-theme-primer

paginate: 5
plugins:
  - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM


