title: Meu Site
description: Bem-vindo ao meu site pessoal!
url: "https://rodrigo-libc.github.io"
baseurl: ""

# Tema oficial (ex.: minima, midnight, slate)
theme: jekyll-theme-midnight

# Paginação
paginate: 5
plugins:
  - jekyll-paginate

# Markdown
markdown: kramdown
kramdown:
  input: GFM


